sideMenuKPI <- function(idDash,idTS,idTop) {
  # Create a namespace function using the provided id
  tagList(
    menuItem("Análisis Univariado", tabName = "kpisNav",
             icon= icon("stats",
                                                          lib="glyphicon")),
    conditionalPanel("input.sidebarMenu == 'kpisNav' & input.kpisTabset == 'TSDash'",
                     selectizeInput(paste0(idTS,"cat"),
                                    label="Variable Categórica a visualizar:",
                                    choices=categoricas,
                                    selected=categoricas[1])),
    conditionalPanel("input.sidebarMenu == 'kpisNav' & input.kpisTabset == 'TS1Dash2'",
                     selectizeInput(paste0(idTS,"num"),
                                    label="Variable numérica a visualizar:",
                                    choices=numericas,
                                    selected=numericas[1])),
    menuItem("Análisis Bivariado", tabName = "kpisNav2",
             icon= icon("stats",
                        lib="glyphicon")),
    conditionalPanel("input.sidebarMenu == 'kpisNav2' & input.kpisTabset2 == 'TS2Dash'",
                     selectizeInput(paste0(idTS,"cat1"),
                                    label="Primer variable categórica a visualizar:",
                                    choices=categoricas,
                                    selected=categoricas[1]),
                      selectizeInput(paste0(idTS,"cat2"),
                                     label="Segunda variable categórica a visualizar:",
                                     choices=categoricas,
                                     selected=categoricas[2])),
    conditionalPanel("input.sidebarMenu == 'kpisNav2' & input.kpisTabset2 == 'TS2Dash2'",
                     selectizeInput(paste0(idTS,"num1"),
                                    label="Primer variable numérica a visualizar (eje x):",
                                    choices=numericas,
                                    selected=numericas[1]),
                     selectizeInput(paste0(idTS,"num2"),
                                    label="Segunda variable numérica a visualizar (eje y):",
                                    choices=numericas,
                                    selected=numericas[2])),
    conditionalPanel("input.sidebarMenu == 'kpisNav2' & input.kpisTabset2 == 'TS2Dash3'",
                     selectizeInput(paste0(idTS,"mix1"),
                                    label="Primer variable a visualizar:",
                                    choices=categoricas,
                                    selected=categoricas[1]),
                     selectizeInput(paste0(idTS,"mix2"),
                                    label="Segunda variable a visualizar:",
                                    choices=numericas,
                                    selected=numericas[1])),
    menuItem("Análisis Multivariado", tabName = "kpisNav3",
             icon= icon("stats",
                        lib="glyphicon")),
    conditionalPanel("input.sidebarMenu == 'kpisNav3' & input.kpisTabset3 == 'TS3Dash'",
                     selectizeInput(paste0(idTS,"mixa1"),
                                    label="Primer variable a visualizar:",
                                    choices=numericas,
                                    selected=numericas[1]),
                     selectizeInput(paste0(idTS,"mixa2"),
                                    label="Segunda variable a visualizar:",
                                    choices=numericas,
                                    selected=numericas[2]),
                     selectizeInput(paste0(idTS,"mixa3"),
                                    label="Tercer variable a visualizar:",
                                    choices=numericas,
                                    selected=numericas[3]),
                     selectizeInput(paste0(idTS,"mixa4"),
                                    label="Cuarta variable a visualizar:",
                                    choices=numericas,
                                    selected=numericas[4]))
    
  
  )
}
