# Comprensión de los datos 

## Recolección de datos

De acuerdo a la documentación disponible[^1], uno de los requisitos necesarios para descargar los datos de visitas de los clientes de Walmart, es aportar la credenciales de un usuario registrado en el Kaggle.

En este caso, para facilitar este proceso, se implementó un programa en Bash, denominado download_extract_data.sh, el cual aprovecha la herramienta Wget de UNIX, para realizar la descarga de los datos del sitio electrónico en comento, recibiendo un archivo de configuración con las credenciales de autenticación de un cierto usuario (archivo cookies.txt).

A su vez, se creó un script en R (wrinting_feather.R, presente en la carpeta /data) que convierte los archivos .csv a formato .feather.

Como resultado, dentro de la carpeta /data se obtiene los siguientes archivo en formato .csv y .feather:

* **test.csv:** el cual contiene los datos del conjunto de entrenamiento,
* **train.csv:** relativo a los datos de entrenamiento, y finalmente,
* **sample_submission.csv:** es un ejemplo del formato en que se deben aportar los datos al sistema de Kaggle para la evaluación del desempeño del modelo de clasificación propuesto para el problema que nos ocupa.
* **test.feather**,
* **train.feather**.

[^1]: Véase https://github.com/Kaggle/kaggle-api

** Instrucciones para descarga de datos**

1. Debemos darle permisos de ejecución al script de Bash que se encuentra en la carpeta */build/comprension_datos* desde la terminal:

```
chmod +x download_extract_data.sh
```
2. Posteriormente ejecutamos dicho programa:

```
./download_extract_data.sh
```

3. Como se ha mencionado, el resultado de la ejecución de este script es la descarga de tres archivos dentro de la carpeta /data (train.csv, test.csv y sample_submission.csv).

## Análisis exploratorio de datos

De acuerdo a la documentación de Kaggle, la información de Walmart se proporciona en términos de las siguientes 7 variables:
  
* **TripType:** Variable objetivo. Son 38 diferentes categorias,
* **Visit Number:**  código identificardor de la visita de un usuario al establecimiento (o simplemente, "viaje"),
* **Weekday:** Día de la semana en que ocurrió el viaje del cliente,
* **UPC** corresponde al número de barras  de cada producto (es decir, un código identidicador del mismo),
* **ScanCount:** relativo al número de productos involucrados en la transacción del cliente. Cabe descatar que si se trada de una devolución, se representa como un número negativo
* **Department Description:** corresponde a una descripción de la categoria a la que pertenece el producto involucrado en la transacción del cliente.
* **Fineline Number:** relativo a un código identificador de 5,196 productos.


### Univariado

### Bivariado

### Multivariado
