--- 
title: "Proyecto Walmart"
author: "Beto, Cesar, Luis y Paola"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
code_folding: "hide"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "El objetivo de libro es describir el proceso de CRISP."
---

```{r eval=FALSE}
#install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
library("bookdown")
```

```{r include=FALSE}
instalar <- function(paquete) {
  if (!require(paquete,character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)) {
    install.packages(as.character(paquete), dependecies = TRUE, repos = "http://cran.us.r-project.org")
    library(paquete, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
  }
}

paquetes <- c("odbc","readr", "stringr", "dplyr", "tidyverse", "bookdown",
              "funModeling","magrittr")

lapply(paquetes, instalar)

# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
  
), 'packages.bib')

```


# Breve descripción del proyecto 

Walmart uses both art and science to continually make progress on their core mission of better understanding and serving their customers. One way Walmart is able to improve customers' shopping experiences is by segmenting their store visits into different trip types. 
